"""links table

Revision ID: 5b049bfa767b
Revises: 69d3777a7e51
Create Date: 2022-06-13 23:37:02.495665

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5b049bfa767b'
down_revision = '69d3777a7e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'link', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('wiki_topic', sa.String(length=100), nullable=True),
        sa.Column('wiki_links', sa.PickleType(), nullable=True),
        sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_link_wiki_links'),
                    'link', ['wiki_links'],
                    unique=True)
    op.create_index(op.f('ix_link_wiki_topic'),
                    'link', ['wiki_topic'],
                    unique=True)
    op.drop_index('ix_links_wiki_links', table_name='links')
    op.drop_index('ix_links_wiki_topic', table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'links', sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('wiki_topic', sa.VARCHAR(length=80), nullable=True),
        sa.Column('wiki_links', sa.BLOB(), nullable=True),
        sa.PrimaryKeyConstraint('id'))
    op.create_index('ix_links_wiki_topic',
                    'links', ['wiki_topic'],
                    unique=False)
    op.create_index('ix_links_wiki_links',
                    'links', ['wiki_links'],
                    unique=False)
    op.drop_index(op.f('ix_link_wiki_topic'), table_name='link')
    op.drop_index(op.f('ix_link_wiki_links'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
